latency-wait: 120
reason: True
rerun-incomplete: True
show-failed-logs: True
keep-going: True
printshellcmds: True
# Cluster submission
jobname: "{rule}.{jobid}"              # Provide a custom name for the jobscript that is submitted to the cluster.
jobs: 600                              #Use at most N CPU cluster/cloud jobs in parallel.

rerun-triggers: 'mtime'

cluster: "qsub -l h_rt={cluster.time} -j y -pe smp 10 -cwd"
cluster-config: "config/cluster.yaml"

# singularity
#use-singularity: True
#singularity-args: "-B tmp"

# Job resources
#set-resources:
#  - helloSingularity:mem_mb=1000
#  - helloSingularity:runtime=00:03:00
#default-resources:
#  - mem_mb=500
#  - runtime="00:01:00"
# Define the number of threads used by rules
#set-threads:
#  - helloSingularity=1