# cluster.yaml - cluster configuration for my Snakefile.
__default__:
  time: '3:00:00'

create_list_input:
  time: '00:05:00'
  cores: 1

dali_run:
  time: '00:20:00'
  cores: 10

broad_seq_search_aa:
  time: '30:00:00'
  cores: 10

retrieve_genomic_context:
  time: '80:00:00'
  cores: 10
