# === Directory- and File Paths
# Path to parent directory where query and database are stored
run: ""

# The pipeline assumes the subdir called <pdb_files_DAT> is under this path
#   The <pdb_files_DAT> is a pre-built file that must be downloaded prior to Snakedali execution
#   Consult the README.md and download it from snakedali's aws bucket
db_dir: ""

# === MMSEQS Configuration
# MMSEQS Database(s) path
mmseqs_db_path: "" # "<my_path>/mmseqs_db"
# MMSEQS parameters string
mmseqs_search_params: "-s 1 --max-seqs 50 --min-ungapped-score 85 -e 1E-05"
mmseqs_clust_params: "--cluster-mode 2 -c 0.5 --min-seq-id 0.95"
# MMSEQS2 n of iterations
mms_n_iterations: 2

# AFDB Fasta file path
#   This file can be downloaded from AFDB's FTP page: https://ftp.ebi.ac.uk/pub/databases/alphafold/
#   Add the path where it's been downloaded
afdb_pkl: "" # "<mypath>/sequences.pkl"

#   The <fseek_clustered_afdb_representatives.txt> is a pre-built file that must be downloaded prior to Snakedali execution
#   Consult the README.md and download it from snakedali's aws bucket
fseek_clustered_representatives: ""

## Database(s) prefix(es)
##   Each item in the list represents: (a) the internal directory where the db is located
##   and (b) the actual prefix used to build each of the mmseqs databases
#db_prefix: ['refseq-bav/mmseqsDB_refseq-bav']

# The pipeline assumes this is where *.pdb files are stored
input_dir: ""

# Window Size
window_size: 10000

# Commonly a temporary directory where intermediate files are generated and purged
#   Set up this environment variable prior to Snakedali execution
tmpdir: '$TMPDIR'

# Path to Dali's binary folder
dali_path: "DaliLite.v5/bin"

# Path to T-COFFEE binary
tcoffee_bin: "" # "<path_to_tcoffee>/.t_coffee/bin/linux/t_coffee"
tcoffee_1st_params: "-aln |input| -output fasta_aln -matrix=blosum30mt"
tcoffee_2nd_params: "-aln |input| -output fasta_aln -matrix=blosum30mt -usetree= |tree|"

#Apptainer/Singularity Container Path
singularity_path: "../apptainer_sif/import_container.sif"

# According to the 'cluster' variable in: profile_sge/config.yaml
threads: 10

# Number of ranks to distribute MPI process
mpi_ranks: 30

# DO NOT CHANGE: Filename prefix for individual lists of entry IDs
dat_id_list_prefix: "list_batch_"

# DO NOT CHANGE: Alphafold ID conversion table
id_convert: "support_data/clustered_AFDB_structure_key.txt"

# === Run-associated variables

# PDB file names without file extensions
#!!! == These files are expected to be found on {input_dir} == !!!
query_name: [""] # e.g.: ["5id6", "4dyn", "4an8"]

# DO NOT CHANGE: Range of batches within the database to be processed
batch_range: [0,2302]
