# === Directory- and File Paths
# Path to parent directory where query and database are stored
run: ""

# The pipeline assumes the subdir called <pdb_files_DAT> is under this path
#   The <pdb_files_DAT> is a pre-built file that must be downloaded prior to Snakedali execution
db_dir: ""

# The pipeline assumes this is where *.dat files are stored
input_dir: ""

# Commonly a temporary directory where intermediate files are generated and purged
#   Set up this environment variable prior to Snakedali execution
tmpdir: '$TMPDIR'

# Path to Dali's binary folder
dali_path: "DaliLite.v5/bin"

# According to the 'cluster' variable in: profile/config.yaml
threads: 10

# Do not change: Filename prefix for individual lists of entry IDs
dat_id_list_prefix: "list_batch_"

# Alphafold ID conversion table
id_convert: "support_data/clustered_AFDB_structure_key.txt"

# === Run-associated variables
# Do not change: Range of batches within the database to be processed
batch_range: [0,2302]

# PDB file names without file extensions
# !!! These files are expected to be found on input_dir !!!
query_name: [""] # e.g.: ["5id6A", "4dynA", "4an8A"]
